/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package base;

import UAS.ObatControl;
import UAS.dataobat;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp5cd
 */
public class InputObat1 extends javax.swing.JInternalFrame {
int x = 0;
private DefaultTableModel model;
    ObatControl ob = new ObatControl();
    dataobat DO = new dataobat();
    List<dataobat> ListObat = new ArrayList<dataobat>();
    /**
     * Creates new form dataobat1
     */
    public InputObat1() throws SQLException {
        initComponents();
        buatTabel();
        showTabel();
        bersih();
        tombolNormal();
        siapIsi(false);
        tampilx();
    }
    private void buatTabel(){
        model = new DefaultTableModel();
        model.addColumn("Kode Obat");
        model.addColumn("Nama Obat");
        model.addColumn("Jenis Obat");
        model.addColumn("Stok");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        jTable1.setModel(model);
    }
    
    private void showTabel(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListObat.clear();
        ListObat=ob.tampil();
        for (x =0; x<ListObat.size(); x++){
            Object[] data = new Object[6];
            data[0]=ListObat.get(x).getKdObat();
            data[1]=ListObat.get(x).getNmObat();
            data[2]=ListObat.get(x).getJnObat();
            data[3]=ListObat.get(x).getJmlstok();
            data[4]=ListObat.get(x).getHgbeli();
            data[5]=ListObat.get(x).getHgjual();
            model.addRow(data);
        }
        
    }
    private void buatKdBarang(){
        ListObat=ob.tampil();
        int a=ListObat.size()-1;
        int no=Integer.parseInt(ListObat.get(a).getKdObat().replace("A-",""))+1;
        kdobat.setText("A-"+no);
        kdobat.setEnabled(false);
    }
    private void siapIsi(boolean a){
        kdobat.setEnabled(a);
        nmobat.setEnabled(a);
        cmbjenis.setEnabled(a);
        tstok.setEnabled(a);
        hgbeli.setEnabled(a);
        hgjual.setEnabled(a);
    }
    
    private void bersih(){
        kdobat.setText("");
        nmobat.setText("");
        cmbjenis.setSelectedItem("Pilih");
        hgbeli.setText("");
        hgjual.setText("");
    }
    
    private void tombolNormal(){
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
    }
    
    private void tombolKembali(){
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
    }
    
    public void tampilx() throws SQLException{
        int jmlobat = ob.getJumlahobat();
        txtjumlah.setText(String.valueOf(jmlobat));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tstok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nmobat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kdobat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hgbeli = new javax.swing.JTextField();
        hgjual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        cmbjenis = new javax.swing.JComboBox<>();
        txtjumlah = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        pn_navbar.setBackground(new java.awt.Color(0, 0, 102));
        pn_navbar.setForeground(new java.awt.Color(255, 255, 255));
        pn_navbar.setPreferredSize(new java.awt.Dimension(950, 75));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INPUT OBAT");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel2)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        pn_content.setBackground(new java.awt.Color(255, 255, 255));
        pn_content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("KODE OBAT");
        pn_content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("CARI BERDASARKAN");
        pn_content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, 30));

        tstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstokActionPerformed(evt);
            }
        });
        pn_content.add(tstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, 31));

        jLabel5.setText("NAMA OBAT");
        pn_content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        pn_content.add(nmobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, 31));

        jLabel6.setText("JENIS OBAT");
        pn_content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setText("JUMLAH STOK");
        pn_content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        pn_content.add(kdobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, 31));

        jLabel8.setText("HARGA BELI");
        pn_content.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));
        pn_content.add(hgbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 150, 31));
        pn_content.add(hgjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 31));

        jLabel9.setText("HARGA JUAL");
        pn_content.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        btntambah.setBackground(new java.awt.Color(153, 153, 153));
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        pn_content.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        btnsimpan.setBackground(new java.awt.Color(51, 0, 204));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        pn_content.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        btnedit.setBackground(new java.awt.Color(0, 204, 51));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        pn_content.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        btnhapus.setBackground(new java.awt.Color(204, 0, 0));
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        pn_content.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Salep", "Sirup", "Botol ", "Kapsul" }));
        cmbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjenisActionPerformed(evt);
            }
        });
        pn_content.add(cmbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 132, 130, 30));

        txtjumlah.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtjumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtjumlah.setText("100");
        txtjumlah.setToolTipText("");
        pn_content.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, 30));

        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        pn_content.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 122, 160, 30));

        jLabel11.setText("NAMA OBAT & JENIS");
        pn_content.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, 30));

        jLabel12.setText("JENIS OBAT");
        pn_content.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, 30));

        jLabel13.setText("JUMLAH OBAT");
        pn_content.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        pn_content.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 340, 620, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pn_navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pn_content, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pn_navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(pn_content, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tstokActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        if(btntambah.getText().equalsIgnoreCase("Tambah")){
            btntambah.setText("Batal");
            bersih();
            siapIsi(true);
            buatKdBarang();
            nmobat.requestFocus();
            tombolKembali();
        }else{
            btntambah.setText("Tambah");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (nmobat.getText().isEmpty() || cmbjenis.getSelectedItem().equals("") || tstok.getText().isEmpty()
            || hgbeli.getText().isEmpty() || hgjual.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Data harus lengkap","STOK BARANG",JOptionPane.INFORMATION_MESSAGE);
        }else{
            DO.setKdObat(kdobat.getText());
            DO.setNmObat(nmobat.getText());
            DO.setJnObat(cmbjenis.getSelectedItem().toString());
            DO.setJmlstok(Integer.parseInt(tstok.getText()));
            DO.setHgbeli(Integer.parseInt(hgbeli.getText()));
            DO.setHgjual(Integer.parseInt(hgjual.getText()));
            if(btntambah.getText().equalsIgnoreCase("Batal")){
                if(ob.tambahObat(DO)==1){
                    JOptionPane.showMessageDialog(null,"Data Telah Disimpan","Stok Barang", JOptionPane.INFORMATION_MESSAGE);
                    buatTabel();
                    showTabel();
                    try {
                        tampilx();
                    } catch (SQLException ex) {
                        Logger.getLogger(InputObat.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Data Gagal Disimpan","Stok Barang",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            if(btnedit.getText().equalsIgnoreCase("Batal")){
                if(ob.editObat(DO)==1){
                    JOptionPane.showMessageDialog(null,"Data Telah Dirubah","Stok Barang",JOptionPane.INFORMATION_MESSAGE);
                    buatTabel();
                    showTabel();
                }else{
                    JOptionPane.showMessageDialog(null,"Data Gagal Dirubah","Stok Barang",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            btntambah.setText("Tambah");
            btnedit.setText("Edit");
            tombolNormal();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if(btnedit.getText().equalsIgnoreCase("Edit")){
            btnedit.setText("Batal");
            siapIsi(true);
            kdobat.setEnabled(false);
            nmobat.requestFocus();
            btntambah.setEnabled(false);
            btnsimpan.setEnabled(true);
            btnhapus.setEnabled(false);
            btnedit.setEnabled(true);
        }else{
            btnedit.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        DO.setKdObat(kdobat.getText());
        int pesan = JOptionPane.showConfirmDialog(null, "Data Akan Dihapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(ob.deleteObat(DO)==1){
            JOptionPane.showMessageDialog(null,"Data Telah Dihapus");
            bersih();
            siapIsi(false);
            tombolNormal();
            showTabel();
            try {
                tampilx();
            } catch (SQLException ex) {
                Logger.getLogger(InputObat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void cmbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjenisActionPerformed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        String cari = null;
        cari =tcari.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListObat.clear();
        ListObat=ob.cariObat(cari);
        for (x=0; x<ListObat.size(); x++){
            Object[] data= new Object [6];
            data[0]=ListObat.get(x).getKdObat();
            data[1]=ListObat.get(x).getNmObat();
            data[2]=ListObat.get(x).getJnObat();
            data[3]=ListObat.get(x).getJmlstok();
            data[4]=ListObat.get(x).getHgbeli();
            data[5]=ListObat.get(x).getHgjual();
            model.addRow(data);
        }
    }//GEN-LAST:event_tcariKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        kdobat.setText(jTable1.getModel().getValueAt(baris, 0).toString());
        nmobat.setText(jTable1.getModel().getValueAt(baris, 1).toString());
        cmbjenis.setSelectedItem(jTable1.getModel().getValueAt(baris, 2).toString());
        tstok.setText(jTable1.getModel().getValueAt(baris, 3).toString());
        hgbeli.setText(jTable1.getModel().getValueAt(baris, 4).toString());
        hgjual.setText(jTable1.getModel().getValueAt(baris, 5).toString());
        siapIsi(false);
        btnhapus.setEnabled(true);
        btnedit.setEnabled(true);
        btntambah.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JTextField hgbeli;
    private javax.swing.JTextField hgjual;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kdobat;
    private javax.swing.JTextField nmobat;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tstok;
    private javax.swing.JLabel txtjumlah;
    // End of variables declaration//GEN-END:variables
}
